import { Menu } from './sharedservice';

export class DefaultMenus{

    static getSubAdminMenus(){
        let subadminpages:Menu[] = [
            { DisplayTitle: 'Member', OriginalTitle:"Member", MobComponent: "Type2Member", WebComponent: "",MobIcon:"person-add", MobLocalImage: "", WebIcon:"", MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Group Session', OriginalTitle:"Group Session", MobComponent: "Type2ManageSession", WebComponent: "", MobIcon:"people", MobLocalImage: "", MobCloudImage: "", WebIcon:"",  WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'School Session', OriginalTitle:"School Session", MobComponent: "Type2SchoolSessionList",WebComponent: "", MobIcon:"school", MobLocalImage: "", MobCloudImage: "", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Holiday Camp', OriginalTitle:"Holiday Camp", MobComponent: "Type2HolidayCamp", WebComponent: "",MobIcon:"tennisball",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Notification', OriginalTitle:"Notification", MobComponent: "Type2notification", WebComponent: "",MobIcon:"md-notifications",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1 },
            { DisplayTitle: 'Payment', OriginalTitle:"Payment", MobComponent: "InnerPaymentMenu", WebComponent: "",MobIcon:"cash",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Booking', OriginalTitle:"Booking", MobComponent: "BookingcontainerPage", WebComponent: "",MobIcon:"bookmark",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Setup', OriginalTitle:"Setup", MobComponent: "Setup", WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1 },
            { DisplayTitle: 'Report', OriginalTitle:"Report", MobComponent: "Type2Report", WebComponent: "",MobIcon:"paper",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'News & Events', OriginalTitle:"News & Events", MobComponent: "EventsandnewsPage", WebComponent: "",MobIcon:"paper",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Notification Centre', OriginalTitle:"Notification Centre", MobComponent: 'NotificationCenter', WebComponent: "",MobIcon:"md-notifications",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2},
            { DisplayTitle: 'Videos', OriginalTitle:"Videos", MobComponent: 'VideomenueslistingPage', WebComponent: "",MobIcon:"videocam",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},
            { DisplayTitle: 'Tournaments', OriginalTitle:"Tournaments", MobComponent: 'TournamentPage', WebComponent: "",MobIcon:"trophy",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1, },
            { DisplayTitle: 'Events', OriginalTitle:"Events", MobComponent: "EventsPage", WebComponent: "",MobIcon:"calendar",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1 },
            { DisplayTitle: 'Membership', OriginalTitle:"Membership", MobComponent: "MembershipRecord", WebComponent: "",MobIcon:"contacts",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1,},
            { DisplayTitle: 'Performance', OriginalTitle:"Performance", MobComponent: "Performancelist", WebComponent: "",MobIcon:"ios-speedometer",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 1},//added by vinod
            { DisplayTitle: 'Tab Config', OriginalTitle:"Tab Config", MobComponent: "Type2TabConfig", WebComponent: "",MobIcon:"cog",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2},
            { DisplayTitle: 'Venue', OriginalTitle:"Venue", MobComponent: "Type2Venue",WebComponent: "",MobIcon:"globe",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2},
            { DisplayTitle: 'School', OriginalTitle:"School", MobComponent: "Type2School", WebComponent: "",MobIcon:"school",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2,},
            { DisplayTitle: 'Term', OriginalTitle:"Term", MobComponent: "Type2Term", WebComponent: "",MobIcon:"calendar",MobLocalImage: "", MobCloudImage:"", WebIcon:"",WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2},
            { DisplayTitle: 'Manage Team', OriginalTitle:"Manage Team", MobComponent: "Type2ManageCoach", WebComponent: "",MobIcon:"body",MobLocalImage: "",WebIcon:"", MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2,},
            { DisplayTitle: 'Promotion', OriginalTitle:"Promotion", MobComponent: "Type2PromotionList", WebComponent: "",MobIcon:"desktop",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2},
            { DisplayTitle: 'Discount Setup', OriginalTitle:"Discount Setup", MobComponent: "Type2DiscountList", WebComponent: "",MobIcon:"options",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Facility Setup', OriginalTitle:"Facility Setup", MobComponent: 'Type2CourtSetupList',WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true,Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Locations', OriginalTitle:"Locations", MobComponent: 'LocationsetupPage', WebComponent: "",MobIcon:"pin",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Membership', OriginalTitle:"Membership", MobComponent: 'MembershipPage',WebComponent: "",MobIcon:"contacts",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Billing', OriginalTitle:"Billing", MobComponent: 'BillingPage', WebComponent: "",MobIcon:"cash",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Member', OriginalTitle:"Member", MobComponent: "Type2ReportMember", WebComponent: "",MobIcon:"people",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 3,},
            { DisplayTitle: 'Group', OriginalTitle:"Group", MobComponent: "Type2ReportSession",WebComponent: "",MobIcon:"people",MobLocalImage: "", MobCloudImage:"", WebIcon:"",WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 3,},
            { DisplayTitle: 'Coach', OriginalTitle:"Coach", MobComponent: "Type2Schedule",WebComponent: "",MobIcon:"ios-clipboard",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 3, },       
            { DisplayTitle: 'Bookings', OriginalTitle:"Bookings", MobComponent: "Type2ReportBooking", WebComponent: "",MobIcon:"book",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 3 },
            { DisplayTitle: 'Email Setup', OriginalTitle:"Email Setup", MobComponent: "Type2EmailSetupList",WebComponent: "",MobIcon:"mail",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Bank Details', OriginalTitle:"Bank Details", MobComponent: "Type2BankDetailsList",WebComponent: "",MobIcon:"cash",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true,Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Help Config', OriginalTitle:"Help Config", MobComponent: "Type2HelpConfig", WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2,},
            { DisplayTitle: 'Staff Attendence', OriginalTitle:"Staff Attendence", MobComponent: "StaffattendancesetupPage",WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Performance', OriginalTitle:"Performance", MobComponent: "PerformanceSetup", WebComponent: "",MobIcon:"md-paper",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2,},//vinod added for challenges
            { DisplayTitle: 'Terms & Conditions', OriginalTitle:"Terms & Conditions", MobComponent: "TermsandconditionsPage", WebComponent: "",MobIcon:"md-paper",MobLocalImage: "",WebIcon:"", MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2,},
            { DisplayTitle: 'Stripe', OriginalTitle:"Stripe", MobComponent: "StripeConnectPage", WebComponent: "",MobIcon:"cog",MobLocalImage: "", MobCloudImage:"", WebIcon:"",WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Activity Price', OriginalTitle:"Activity Price", MobComponent: "ActivityPrice",WebComponent: "",MobIcon:"ios-cash", MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Wallet', OriginalTitle:"Wallet", MobComponent: "LoyaltySetupPage", WebComponent: "",MobIcon:"",MobLocalImage: "assets/imgs/wallet.svg", WebIcon:"",MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'App Design', OriginalTitle:"App Design", MobComponent: "AppuIconfig", WebComponent: "",MobIcon:"",MobLocalImage: "assets/images/app.svg", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'Category', OriginalTitle:"Category", MobComponent: "CategoryNsubcategory",WebComponent: "",MobIcon:"ios-keypad",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2, },
            { DisplayTitle: 'World Sports', OriginalTitle:"World Sports", MobComponent: "WorldsportlistPage", WebComponent: "",MobIcon:"paper",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:true, WebAccess:true, Role: 2, Type: 2, Level: 2 }];
    
          return subadminpages;
      }

    
      static getCoachMenus(){
          //for the coach add admin menus along with coach menu and make admin menu nodes MobAccess to false
  //and when trying to change coach to admin in coac edit page we need to show menus as per the dropdown of user Types
  //if we select admin show admin menus except coach menus and if we select coach as type only show admin menus
        const coachmenus:Menu[] = [
            { DisplayTitle: 'Member', OriginalTitle: "Member", MobComponent: "CoachMember", WebComponent: "", MobIcon: "person-add", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 1, Level: 1, },
            { DisplayTitle: 'Group Session', OriginalTitle: "Group Session", MobComponent: "CoachManageSession", WebComponent: "", MobIcon: "people", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 1, Level: 1, },
            { DisplayTitle: 'School Session', OriginalTitle: "School Session", MobComponent: "CoachSchoolSessionList", WebComponent: "", MobIcon: "school", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 2, Level: 1 },
            { DisplayTitle: 'Holiday Camp', OriginalTitle: "Holiday Camp", MobComponent: "Type2HolidayCamp", WebComponent: "", MobIcon: "tennisball", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 2, Level: 1 },
            { DisplayTitle: 'Notification', OriginalTitle: "Notification", MobComponent: "CoachNotification", WebComponent: "", MobIcon: "md-notifications", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 2, Level: 1, },
            { DisplayTitle: 'Booking', OriginalTitle: "Booking", MobComponent: "BookingcontainerPage", WebComponent: "", MobIcon: "bookmark", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 2, Level: 1 },
            { DisplayTitle: 'Tournaments', OriginalTitle: "Tournaments", MobComponent: "TournamentPage", WebComponent: "", MobIcon: "trophy", MobLocalImage: "", MobCloudImage: "", WebIcon: "", WebLocalImage: "", WebCloudImage: "", MobileAccess: true, WebAccess: true, Role: 2, Type: 2, Level: 1 },

          // coach menus along with admin menus with MobAccess&WebAccess as false defaultly
                    
        { DisplayTitle: 'Member', OriginalTitle:"Member", MobComponent: "Type2Member", WebComponent: "",MobIcon:"person-add", MobLocalImage: "", WebIcon:"", MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Group Session', OriginalTitle:"Group Session", MobComponent: "Type2ManageSession", WebComponent: "", MobIcon:"people", MobLocalImage: "", MobCloudImage: "", WebIcon:"",  WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'School Session', OriginalTitle:"School Session", MobComponent: "Type2SchoolSessionList",WebComponent: "", MobIcon:"school", MobLocalImage: "", MobCloudImage: "", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Holiday Camp', OriginalTitle:"Holiday Camp", MobComponent: "Type2HolidayCamp", WebComponent: "",MobIcon:"tennisball",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Notification', OriginalTitle:"Notification", MobComponent: "Type2notification", WebComponent: "",MobIcon:"md-notifications",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1 },
        { DisplayTitle: 'Payment', OriginalTitle:"Payment", MobComponent: "InnerPaymentMenu", WebComponent: "",MobIcon:"cash",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Booking', OriginalTitle:"Booking", MobComponent: "BookingcontainerPage", WebComponent: "",MobIcon:"bookmark",MobLocalImage: "", MobCloudImage:"", WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Setup', OriginalTitle:"Setup", MobComponent: "Setup", WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1 },
        { DisplayTitle: 'Report', OriginalTitle:"Report", MobComponent: "Type2Report", WebComponent: "",MobIcon:"paper",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'News & Events', OriginalTitle:"News & Events", MobComponent: "EventsandnewsPage", WebComponent: "",MobIcon:"paper",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Notification Centre', OriginalTitle:"Notification Centre", MobComponent: 'NotificationCenter', WebComponent: "",MobIcon:"md-notifications",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2},
        { DisplayTitle: 'Videos', OriginalTitle:"Videos", MobComponent: 'VideomenueslistingPage', WebComponent: "",MobIcon:"videocam",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},
        { DisplayTitle: 'Tournaments', OriginalTitle:"Tournaments", MobComponent: 'TournamentPage', WebComponent: "",MobIcon:"trophy",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1, },
        { DisplayTitle: 'Events', OriginalTitle:"Events", MobComponent: "EventsPage", WebComponent: "",MobIcon:"calendar",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1 },
        { DisplayTitle: 'Membership', OriginalTitle:"Membership", MobComponent: "MembershipRecord", WebComponent: "",MobIcon:"contacts",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1,},
        { DisplayTitle: 'Performance', OriginalTitle:"Performance", MobComponent: "Performancelist", WebComponent: "",MobIcon:"ios-speedometer",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 1},//added by vinod
        { DisplayTitle: 'Tab Config', OriginalTitle:"Tab Config", MobComponent: "Type2TabConfig", WebComponent: "",MobIcon:"cog",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2},
        { DisplayTitle: 'Venue', OriginalTitle:"Venue", MobComponent: "Type2Venue",WebComponent: "",MobIcon:"globe",MobLocalImage: "", MobCloudImage:"", WebLocalImage: "",WebIcon:"", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2},
        { DisplayTitle: 'School', OriginalTitle:"School", MobComponent: "Type2School", WebComponent: "",MobIcon:"school",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2,},
        { DisplayTitle: 'Term', OriginalTitle:"Term", MobComponent: "Type2Term", WebComponent: "",MobIcon:"calendar",MobLocalImage: "", MobCloudImage:"", WebIcon:"",WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2},
        { DisplayTitle: 'Manage Team', OriginalTitle:"Manage Team", MobComponent: "Type2ManageCoach", WebComponent: "",MobIcon:"body",MobLocalImage: "",WebIcon:"", MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2,},
        { DisplayTitle: 'Promotion', OriginalTitle:"Promotion", MobComponent: "Type2PromotionList", WebComponent: "",MobIcon:"desktop",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2},
        { DisplayTitle: 'Discount Setup', OriginalTitle:"Discount Setup", MobComponent: "Type2DiscountList", WebComponent: "",MobIcon:"options",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Facility Setup', OriginalTitle:"Facility Setup", MobComponent: 'Type2CourtSetupList',WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false,Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Locations', OriginalTitle:"Locations", MobComponent: 'LocationsetupPage', WebComponent: "",MobIcon:"pin",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Membership', OriginalTitle:"Membership", MobComponent: 'MembershipPage',WebComponent: "",MobIcon:"contacts",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Billing', OriginalTitle:"Billing", MobComponent: 'BillingPage', WebComponent: "",MobIcon:"cash",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Member', OriginalTitle:"Member", MobComponent: "Type2ReportMember", WebComponent: "",MobIcon:"people",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 3,},
        { DisplayTitle: 'Group', OriginalTitle:"Group", MobComponent: "Type2ReportSession",WebComponent: "",MobIcon:"people",MobLocalImage: "", MobCloudImage:"", WebIcon:"",WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 3,},
        { DisplayTitle: 'Coach', OriginalTitle:"Coach", MobComponent: "Type2Schedule",WebComponent: "",MobIcon:"ios-clipboard",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 3, },       
        { DisplayTitle: 'Bookings', OriginalTitle:"Bookings", MobComponent: "Type2ReportBooking", WebComponent: "",MobIcon:"book",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 3 },
        { DisplayTitle: 'Email Setup', OriginalTitle:"Email Setup", MobComponent: "Type2EmailSetupList",WebComponent: "",MobIcon:"mail",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Bank Details', OriginalTitle:"Bank Details", MobComponent: "Type2BankDetailsList",WebComponent: "",MobIcon:"cash",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false,Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Help Config', OriginalTitle:"Help Config", MobComponent: "Type2HelpConfig", WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2,},
        { DisplayTitle: 'Staff Attendence', OriginalTitle:"Staff Attendence", MobComponent: "StaffattendancesetupPage",WebComponent: "",MobIcon:"settings",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Performance', OriginalTitle:"Performance", MobComponent: "PerformanceSetup", WebComponent: "",MobIcon:"md-paper", MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2,},//vinod added for challenges
        { DisplayTitle: 'Terms & Conditions', OriginalTitle:"Terms & Conditions", MobComponent: "TermsandconditionsPage", WebComponent: "",MobIcon:"md-paper",MobLocalImage: "",WebIcon:"", MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2,},
        { DisplayTitle: 'Stripe', OriginalTitle:"Stripe", MobComponent: "StripeConnectPage", WebComponent: "",MobIcon:"cog",MobLocalImage: "", MobCloudImage:"", WebIcon:"",WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Activity Price', OriginalTitle:"Activity Price", MobComponent: "ActivityPrice",WebComponent: "",MobIcon:"ios-cash", MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Wallet', OriginalTitle:"Wallet", MobComponent: "LoyaltySetupPage", WebComponent: "",MobIcon:"",MobLocalImage: "assets/imgs/wallet.svg", WebIcon:"",MobCloudImage:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'App Design', OriginalTitle:"App Design", MobComponent: "AppuIconfig", WebComponent: "",MobIcon:"",MobLocalImage: "assets/images/app.svg", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'Category', OriginalTitle:"Category", MobComponent: "CategoryNsubcategory",WebComponent: "",MobIcon:"ios-keypad",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2, },
        { DisplayTitle: 'World Sports', OriginalTitle:"World Sports", MobComponent: "WorldsportlistPage", WebComponent: "",MobIcon:"paper",MobLocalImage: "", MobCloudImage:"",WebIcon:"", WebLocalImage: "", WebCloudImage:"",MobileAccess:false, WebAccess:false, Role: 2, Type: 2, Level: 2 }];
        
        return coachmenus;
      }





    
}